#!/bin/bash


# place this file in /usr/local/bin/tmp-mount
# to let anyone use this command use, add the following to the !!END!! of the sudoers file:
# ALL ALL=NOPASSWD: /usr/local/bin/tmp-mount
# and don't forget to chmod +x this file!

MANAGED_SOFTWARE_DIR=/opt/applications/SPMLauncher/ManagedSoftware
MOUNT_DIR=/tmp/SPMLauncher

if [ "$1" = "-m" ] ; then
        /bin/mount --bind $MANAGED_SOFTWARE_DIR/$2 $MOUNT_DIR/$3
elif [ "$1" = "-u" ] ; then
        /bin/umount $MOUNT_DIR/$2
fi
